### ISSUE TITLE
/vsi-podcasti/ dups

### ISSUE THREAD

**Issue by roks0n** [roks0n/podcasti.si#129]
See example bellow, for some reason O is represented twice. This issue occurs for some other letters as well.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/889696/78160359-1b218080-7444-11ea-86d7-03bf98e1b091.png">

**Comment by romunov** [comment]
Looks good now?

![image](https://user-images.githubusercontent.com/544571/200110714-528a5a7d-9f02-45f2-9f8c-3e7fe37f0b0f.png)

**Comment by roks0n** [comment]
Seems so! :)
